export const ACTION = {
  FETCH_LIST_SUCCESS: "FETCH_ALL_SUCCESS",
  FETCH_LIST_FAILURE: "FETCH_ALL_FAILURE",
  UPDATE_SUCCESS: "UPDATE_SUCCESS",
  UPDATE_FAILURE: "UPDATE_FAILURE"
};
export const REQUEST_STATUS = {
  LOADING: "loading",
  SUCCESS: "success",
  ERROR: "error"
};
